build:
  name: Frontend Docker Build
  runs-on: ubuntu-latest

  needs:
    - lint
    - test

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      working-directory: starter/frontend
      env:
        REACT_APP_MOVIE_API_URL: http://localhost:5000
      run: |
        docker build \
          --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL \
          --tag mp-frontend:${{ github.sha }} .